version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgis
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    networks:
      - my_network
    ports:
      - "2222:5432"
  app:
    image: phborba/pytorch_segmentation_models
    build: .
    container_name: pytorch_segmentation_models
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - my_network
networks:
  my_network:
